const LOAD_CAREER_SUCCESS = "LOAD_CAREER_SUCCESS";

const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

const TOGGLE_MENU = "TOGGLE_MENU";

const NEWS_LOADED = "NEWS_LOADED";

export {
  LOAD_CAREER_SUCCESS,
  BEGIN_AJAX_CALL,
  AJAX_CALL_ERROR,
  TOGGLE_MENU,
  NEWS_LOADED
};
